controller_list:
  - name: "prbt/manipulator_joint_trajectory_controller/"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [prbt_joint_1, prbt_joint_2, prbt_joint_3, prbt_joint_4, prbt_joint_5, prbt_joint_6]
