# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  prbt_joint_1:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 3.49
  prbt_joint_2:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 3.49
  prbt_joint_3:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 3.49
  prbt_joint_4:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 3.49
  prbt_joint_5:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 3.49
  prbt_joint_6:
    has_velocity_limits: true
    max_velocity: 1.57
    has_acceleration_limits: true
    max_acceleration: 3.49
