# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial  # distro used by Travis (bionic not yet available), moveit_ci uses the docker image's distro
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  global:
    - MOVEIT_CI_TRAVIS_TIMEOUT=85  # Travis grants us 90 min, but we add a safety margin of 5 min
    - ROS_DISTRO=dashing
    - ROS_REPO=ros
    - UPSTREAM_WORKSPACE=moveit2.repos
    - TEST_BLACKLIST=moveit_ros_perception moveit_core # mesh_filter_test fails due to broken Mesa OpenGL
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-function"
    - WARNINGS_OK=false
  matrix:
    # TODO(mlautman): Enable these in the future once they pass
    # - TEST="clang-format ament_lint"
    - ROS_DISTRO=dashing

# TODO(mlautman): Enable once franka_ikfast_plugin and panda_ikfast_plugin are available
# matrix: # Add a separate config to the matrix, using clang as compiler
  # include:
    # # add a config to the matrix using clang as compiler and also test ikfast plugin creation
    # - compiler: clang
      # env: ROS_REPO=ros
           # BEFORE_DOCKER_SCRIPT="source moveit_kinematics/test/test_ikfast_plugins.sh"
           # CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wno-unused-function -Wno-overloaded-virtual"

before_script:
  - git clone -q -b pr-ros2_vcstool_support --depth=1 https://github.com/PickNikRobotics/moveit_ci.git .moveit_ci

script:
  - .moveit_ci/travis.sh
