#
# Copyright Â© 2018 Pilz GmbH & Co. KG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# FILE DESCRIPTION:
#
# This file mappes the robot joints to the corresponding CAN-IDs. In this file
# only the robot joints are considered (no gripper joint).
#

name: manipulator

bus:
  device: can0
sync:
  interval_ms: 10
  overflow: 0

defaults:
  eds_pkg: moveit_resources_prbt_support
  eds_file: "config/prbt_0_1.dcf"

nodes:
  prbt_joint_1:
    id: 3
    braketest_required: true
  prbt_joint_2:
    id: 4
    braketest_required: true
  prbt_joint_3:
    id: 5
    braketest_required: true
  prbt_joint_4:
    id: 6
    braketest_required: true
  prbt_joint_5:
    id: 7
    braketest_required: true
  prbt_joint_6:
    id: 8
    braketest_required: true
