name: docker

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling, galactic]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_ID: ghcr.io/${{ github.repository_owner }}/moveit2
      VERSION: ${{ matrix.ROS_DISTRO }}-${{ github.job }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          echo Building docker ${{ env.IMAGE_ID }}:${{ env.VERSION }}
          docker build . --build-arg ROS_DISTRO=${{ matrix.ROS_DISTRO }} --file .docker/${{ github.job }}/Dockerfile --tag ${{ env.IMAGE_ID }}:${{ env.VERSION }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ${{ env.IMAGE_ID }}:${{ env.VERSION }}

  ci:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling, galactic]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_ID: ghcr.io/${{ github.repository_owner }}/moveit2
      VERSION: ${{ matrix.ROS_DISTRO }}-${{ github.job }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          echo Building docker ${{ env.IMAGE_ID }}:${{ env.VERSION }}
          docker build . --build-arg ROS_DISTRO=${{ matrix.ROS_DISTRO }} --file .docker/${{ github.job }}/Dockerfile --tag ${{ env.IMAGE_ID }}:${{ env.VERSION }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ${{ env.IMAGE_ID }}:${{ env.VERSION }}

  ci-testing:
    needs: ci
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling, galactic]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_ID: ghcr.io/${{ github.repository_owner }}/moveit2
      VERSION: ${{ matrix.ROS_DISTRO }}-${{ github.job }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          echo Building docker ${{ env.IMAGE_ID }}:${{ env.VERSION }}
          docker build . --build-arg ROS_DISTRO=${{ matrix.ROS_DISTRO }} --file .docker/${{ github.job }}/Dockerfile --tag ${{ env.IMAGE_ID }}:${{ env.VERSION }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ${{ env.IMAGE_ID }}:${{ env.VERSION }}

  source:
    needs: ci-testing
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling, galactic]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_ID: ghcr.io/${{ github.repository_owner }}/moveit2
      VERSION: ${{ matrix.ROS_DISTRO }}-${{ github.job }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          echo Building docker ${{ env.IMAGE_ID }}:${{ env.VERSION }}
          docker build . --build-arg ROS_DISTRO=${{ matrix.ROS_DISTRO }} --file .docker/${{ github.job }}/Dockerfile --tag ${{ env.IMAGE_ID }}:${{ env.VERSION }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ${{ env.IMAGE_ID }}:${{ env.VERSION }}
