# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: BuildAndTest

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {
            ROS_DISTRO: foxy, ROS_REPO: main, CCOV_UPLOAD: true,
            TARGET_CMAKE_ARGS: "-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS='--coverage' -DCMAKE_CXX_FLAGS='--coverage' --no-warn-unused-cli",
            AFTER_RUN_TARGET_TEST: './.ci.prepare_codecov',
            ADDITIONAL_DEBS: 'lcov'
          }
          # - {ROS_DISTRO: foxy, ROS_REPO: testing, CCOV_UPLOAD: false}
    env:
      UPSTREAM_WORKSPACE: moveit2.repos
      CCACHE_DIR: /home/runner/.ccache
      BASEDIR: .base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: always-upload-cache
        uses: pat-s/always-upload-cache@v2.1.3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-${{ github.sha }}-${{ github.job }}  
          restore-keys: |
            ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}-${{ github.sha }}
            ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: ${{ env.BASEDIR }}/target_ws/**/test_results/**/*.xml
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.env.CCOV_UPLOAD }} 
        with:
          files: ${{ env.BASEDIR }}/coverage.info
