name: "Tutorial Docker Images"

on:
  schedule:
    # 5 PM UTC every Sunday
    - cron:  '0 17 * * 6'
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  tutorial-source:
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [rolling, jazzy]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      GH_IMAGE: ghcr.io/moveit/moveit2:main-${{ matrix.ROS_DISTRO }}-${{ github.job }}
      DH_IMAGE: moveit/moveit2:main-${{ matrix.ROS_DISTRO }}-${{ github.job }}
      PUSH: ${{ (github.event_name != 'pull_request') && (github.repository == 'moveit/moveit2') }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        if: env.PUSH == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        if: env.PUSH == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Remove .dockerignore"
        run: rm .dockerignore  # enforce full source context
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: docker-tutorial-ccache-${{ matrix.ROS_DISTRO }}-${{ hashFiles( '.docker/tutorial-source/Dockerfile' ) }}
      - name: inject ccache into docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.2
        with:
          cache-source: .ccache
          cache-target: /root/.ccache/
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .docker/${{ github.job }}/Dockerfile
          build-args: ROS_DISTRO=${{ matrix.ROS_DISTRO }}
          push: ${{ env.PUSH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.GH_IMAGE }}
            ${{ env.DH_IMAGE }}

  delete_untagged:
    runs-on: ubuntu-latest
    needs:
      - tutorial-source
    steps:
      - name: Delete Untagged Images
        if: (github.event_name != 'pull_request') && (github.repository == 'moveit/moveit2')
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.DELETE_PACKAGES_TOKEN }}
          script: |
            const response = await github.request("GET /orgs/${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions", {
                per_page: ${{ env.PER_PAGE }}
              });
            for(version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                    console.log("delete " + version.id)
                    const deleteResponse = await github.request("DELETE /orgs/${{ env.OWNER }}/packages/container/${{ env.PACKAGE_NAME }}/versions/" + version.id, { });
                    console.log("status " + deleteResponse.status)
                }
            }
        env:
          OWNER: moveit
          PACKAGE_NAME: moveit2
          PER_PAGE: 100
